# Generated by Django 3.1.8 on 2021-06-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210611_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
