# Generated by Django 3.1.8 on 2021-06-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210611_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
